from: markdown+tex_math_dollars+raw_attribute+inline_code_attributes+definition_lists+implicit_figures+citations
# yaml_metadata_block +grid_tables+pipe_tables+simple_tables
to: pdf
# texlive-xelatex
pdf-engine: xelatex
# texlive-textcase texlive-fvextra
include-in-header: config/preamble.tex
standalone: true
fail-if-warnings: true
# Manually in report.md
# table-of-contents: true
# toc-depth: 2
number-sections: true